#ifndef GUI_SETTINGS_AUDIO_H
#define GUI_SETTINGS_AUDIO_H

LAYOUT_AddChild, IIntuition->NewObject(LayoutClass, NULL, //"layout.gadget",
  LAYOUT_BevelStyle,     BVS_SBAR_VERT,
  LAYOUT_Label,          GetString(&li, MSG_GUI_SETTINGS_SND_GROUP),//"Audio Options",

LAYOUT_AddChild, IIntuition->NewObject(SpaceClass, NULL, TAG_DONE),

             LAYOUT_AddChild, OBJ(OID_AHI_OPTIONS) = IIntuition->NewObject(LayoutClass, NULL, //"layout.gadget",
              LAYOUT_Orientation,    LAYOUT_ORIENT_VERT,
              LAYOUT_HorizAlignment, LALIGN_RIGHT,
              LAYOUT_SpaceOuter,     TRUE,
//LAYOUT_BevelStyle, BVS_GROUP,
               LAYOUT_AddChild, OBJ(OID_AHI_PBR) = IIntuition->NewObject(ChooserClass, NULL, //"chooser.gadget",
                GA_ID,         OID_AHI_PBR,
                GA_RelVerify,  TRUE,
                GA_Underscore, 0,
                GA_TabCycle,   TRUE,
                //CHOOSER_Labels,   &ahi_pbr_list,
                CHOOSER_LabelArray, ahi_pbr,
                CHOOSER_Selected, 0,
                //CHOOSER_Justification, CHJ_RIGHT,
               TAG_DONE),
//               CHILD_WeightedWidth, 0,
               CHILD_Label, IIntuition->NewObject(LabelClass, NULL,// "label.image",
                LABEL_Text, GetString(&li, MSG_GUI_SETTINGS_SND_PLAYBACK),//"_AHI Playback",
               TAG_DONE),
//               CHILD_WeightedWidth, 0,
               /*LAYOUT_AddChild, OBJ(OID_AHI_BUF) = IIntuition->NewObject(ChooserClass, NULL, //"chooser.gadget",
                //GA_ID,         OID_AHI_BUF,
                //GA_RelVerify,  TRUE,
                GA_Underscore, 0,
                //CHOOSER_Labels,   &ahi_buf_list,
                CHOOSER_LabelArray, ahi_buf,
                CHOOSER_Selected, 0,
                //CHOOSER_Justification, CHJ_RIGHT,
               TAG_DONE),*/
               LAYOUT_AddChild, OBJ(OID_AHI_BUF) = IIntuition->NewObject(SliderClass, NULL,
                //GA_ID,        OID_AHI_BUF,
                //GA_RelVerify, FALSE,
                GA_TabCycle, TRUE,
                SLIDER_Min,  0, // 210 -> as when saving/loading this is "index" 0
                SLIDER_Max, 11, //  32 -> see ahibuf_lvlHook()
                SLIDER_Invert, TRUE,
                SLIDER_Ticks,      7,
                SLIDER_ShortTicks, TRUE,
                SLIDER_LevelMaxLen, 6,
                SLIDER_Orientation, SORIENT_HORIZ,
                SLIDER_LevelHook,   ahibuf_lvlHook,
                SLIDER_LevelFormat, "%ld ms",
                //SLIDER_LevelPlace,  PLACETEXT_IN,
               TAG_DONE),
//               CHILD_WeightedWidth,  0,
               //CHILD_WeightedHeight, 0,
               CHILD_Label, IIntuition->NewObject(LabelClass, NULL,// "label.image",
                LABEL_Text, GetString(&li, MSG_GUI_SETTINGS_SND_BUFFER),//" _Buffer length",
               TAG_DONE),
               LAYOUT_AddChild, OBJ(OID_AHI_SYNC) = IIntuition->NewObject(CheckBoxClass, NULL, //"checkbox.gadget",
                //GA_ID,   OID_AHI_SYNC,
                //GA_RelVerify, TRUE,
                GA_TabCycle, TRUE,
                GA_Text,     GetString(&li, MSG_GUI_SETTINGS_SND_SYNC),//"Synchroni_zed",
                CHECKBOX_TextPlace, PLACETEXT_LEFT,
               TAG_DONE),
               CHILD_WeightedWidth, 0,
               LAYOUT_AddChild, OBJ(OID_AHI_NOST) = IIntuition->NewObject(CheckBoxClass, NULL, //"checkbox.gadget",
                //GA_ID,   OID_AHI_NOST,
                //GA_RelVerify, TRUE,
                GA_TabCycle, TRUE,
                GA_Text,     GetString(&li, MSG_GUI_SETTINGS_SND_NOST),//"_No stereo",
                CHECKBOX_TextPlace, PLACETEXT_LEFT,
               TAG_DONE),
//               CHILD_WeightedWidth, 0,
                LAYOUT_AddChild, OBJ(OID_SND_IMETHOD) = IIntuition->NewObject(ChooserClass, NULL, //"chooser.gadget",
                 //GA_ID,         OID_SND_IMETHOD,
                 //GA_RelVerify,  TRUE,
                 GA_Underscore, 0,
                 GA_TabCycle,   TRUE,
                 CHOOSER_Labels,   &snd_imet_list,
                 CHOOSER_Selected, 0,
                 //CHOOSER_Justification, CHJ_RIGHT,
                TAG_DONE),
//                CHILD_WeightedWidth, 0,
                CHILD_Label, IIntuition->NewObject(LabelClass, NULL,// "label.image",
                 LABEL_Text, GetString(&li, MSG_GUI_SETTINGS_SND_INTERPOL),//"TurboFrameSkip",
                TAG_DONE),
                LAYOUT_AddChild, OBJ(OID_SND_THREAD) = IIntuition->NewObject(CheckBoxClass, NULL, //"checkbox.gadget",
                 //GA_ID,   OID_SND_THREAD,
                 //GA_RelVerify, TRUE,
                 GA_TabCycle, TRUE,
                 GA_Text,     GetString(&li, MSG_GUI_SETTINGS_SND_THREAD),//"Sound thread",
                 CHECKBOX_TextPlace, PLACETEXT_LEFT,
                TAG_DONE),
//                CHILD_WeightedWidth, 0,
             TAG_DONE),
             CHILD_WeightedWidth, 0,

  LAYOUT_AddChild, IIntuition->NewObject(SpaceClass, NULL, TAG_DONE),

TAG_DONE), // END of 'Audio Options'

#endif
