#ifndef GUI_SETTINGS_ENGINE_H
#define GUI_SETTINGS_ENGINE_H

LAYOUT_AddChild, IIntuition->NewObject(LayoutClass, NULL, //"layout.gadget",
  LAYOUT_BevelStyle, BVS_SBAR_VERT,
  LAYOUT_Label,      GetString(&li, MSG_GUI_SETTINGS_ENGINE_OPTIONS),//"Engine Options",

  LAYOUT_AddChild, IIntuition->NewObject(SpaceClass, NULL, TAG_DONE),

             LAYOUT_AddChild, OBJ(OID_ENGINE_OPTIONS) = IIntuition->NewObject(LayoutClass, NULL, //"layout.gadget",
              LAYOUT_Orientation,    LAYOUT_ORIENT_VERT,
              LAYOUT_HorizAlignment, LALIGN_RIGHT,
              LAYOUT_SpaceOuter,     TRUE,
//LAYOUT_BevelStyle, BVS_GROUP,
              LAYOUT_AddChild, OBJ(OID_HACKVIDEO_GROUP) = IIntuition->NewObject(LayoutClass, NULL, //"layout.gadget",
                LAYOUT_SpaceInner, FALSE,
//LAYOUT_BevelStyle, BVS_GROUP,
                LAYOUT_AddChild, OBJ(OID_HACKVIDEO) = IIntuition->NewObject(CheckBoxClass, NULL, //"checkbox.gadget",
                 GA_ID,        OID_HACKVIDEO,
                 GA_RelVerify, TRUE,
                 GA_Text,      GetString(&li, MSG_GUI_SETTINGS_ENG_VIDEOHACK),//"Video Hack",
                 CHECKBOX_TextPlace, PLACETEXT_LEFT,
                TAG_DONE),
                //CHILD_WeightedWidth, 0,
                LAYOUT_AddChild, OBJ(OID_HV_WIDTH) = IIntuition->NewObject(IntegerClass, NULL, //"integer.gadget",
                 //GA_ID,       OID_HV_WIDTH,
                 //GA_RelVerify, TRUE,
                 GA_Disabled, TRUE,
                 INTEGER_Number,  cfg_value[_HV_WIDTH],
                 INTEGER_Minimum,  640,
                 INTEGER_Maximum, 8192,
                 INTEGER_MinVisible, 5,
                 INTEGER_MaxChars,   4,
                TAG_DONE),
                LAYOUT_AddChild, OBJ(OID_HV_HEIGHT) = IIntuition->NewObject(IntegerClass, NULL, //"integer.gadget",
                 //GA_ID,       OID_HV_HEIGHT,
                 //GA_RelVerify, TRUE,
                 GA_Disabled, TRUE,
                 INTEGER_Number,  cfg_value[_HV_HEIGHT],
                 INTEGER_Minimum,  480,
                 INTEGER_Maximum, 4320,
                 INTEGER_MinVisible, 5,
                 INTEGER_MaxChars,   4,
                TAG_DONE),
                CHILD_Label, IIntuition->NewObject(LabelClass, NULL,// "label.image",
                 LABEL_Text, " x",
                TAG_DONE),
                //CHILD_WeightedWidth, 0,
               TAG_DONE),
//               CHILD_WeightedWidth, 0,
               LAYOUT_AddChild, OBJ(OID_SPRITE_LIMIT) = IIntuition->NewObject(CheckBoxClass, NULL, //"checkbox.gadget",
                //GA_ID,   OID_SPRITE_LIMIT,
                //GA_RelVerify, TRUE,
                GA_Text, GetString(&li, MSG_GUI_SETTINGS_DISABLESPRITELIMIT),//"No Overscan (320x240)",
                CHECKBOX_TextPlace, PLACETEXT_LEFT,
               TAG_DONE),
//               CHILD_WeightedWidth, 0,
               LAYOUT_AddChild, OBJ(OID_MSU1) = IIntuition->NewObject(CheckBoxClass, NULL, //"checkbox.gadget",
                //GA_ID,   OID_MSU1,
                //GA_RelVerify, TRUE,
                GA_Text, GetString(&li, MSG_GUI_SETTINGS_MSU1),//"Activate MSU1",
                CHECKBOX_TextPlace, PLACETEXT_LEFT,
               TAG_DONE),
//               CHILD_WeightedWidth, 0,
               LAYOUT_AddChild, OBJ(OID_TURBO_FSF) = IIntuition->NewObject(ChooserClass, NULL, //"chooser.gadget",
                 //GA_ID,         OID_TURBO_FSF,
                 //GA_RelVerify,  TRUE,
                 GA_Underscore, 0,
                 CHOOSER_Labels,   &turbofs_list,
                 CHOOSER_Selected, 0,
                 //CHOOSER_Justification, CHJ_RIGHT,
                TAG_DONE),
//                CHILD_WeightedWidth, 0,
                CHILD_Label, IIntuition->NewObject(LabelClass, NULL,// "label.image",
                 LABEL_Text, GetString(&li, MSG_GUI_SETTINGS_ENG_ACTIVETFRAMESKIP),//"TurboFrameSkip",
                TAG_DONE),
             TAG_DONE),
             CHILD_WeightedWidth, 0,

  LAYOUT_AddChild, IIntuition->NewObject(SpaceClass, NULL, TAG_DONE),

TAG_DONE), // END of 'Engine Options'

#endif
