#ifndef GUI_SETTINGS_GRAPHICS_H
#define GUI_SETTINGS_GRAPHICS_H

LAYOUT_AddChild, IIntuition->NewObject(LayoutClass, NULL, //"layout.gadget",
  LAYOUT_BevelStyle,     BVS_SBAR_VERT,
  LAYOUT_Label,          GetString(&li, MSG_GUI_SETTINGS_GFX_GROUP),//"Graphics Options",

  LAYOUT_AddChild, IIntuition->NewObject(SpaceClass, NULL, TAG_DONE),

  LAYOUT_AddChild, OBJ(OID_GFX_OPTIONS) = IIntuition->NewObject(LayoutClass, NULL, //"layout.gadget",
    LAYOUT_Orientation,    LAYOUT_ORIENT_VERT,
    LAYOUT_HorizAlignment, LALIGN_RIGHT,
    LAYOUT_SpaceOuter,     TRUE,
//LAYOUT_BevelStyle,     BVS_GROUP,
    LAYOUT_AddChild, OBJ(OID_INTERLEAVE) = IIntuition->NewObject(CheckBoxClass, NULL, //"checkbox.gadget",
      //GA_ID,   OID_INTERLEAVE,
      //GA_RelVerify, TRUE,
      GA_Text, GetString(&li, MSG_GUI_SETTINGS_GFX_NOINTERLEAVE),//"Disabl_e interleave",
      CHECKBOX_TextPlace, PLACETEXT_LEFT,
    TAG_DONE),
//    CHILD_WeightedWidth, 0,
    LAYOUT_AddChild, OBJ(OID_MEMMAP) = IIntuition->NewObject(ChooserClass, NULL, //"chooser.gadget",
      //GA_ID,         OID_MEMMAP,
      //GA_RelVerify,  TRUE,
      GA_Underscore, 0,
      CHOOSER_Labels,   &memmap_list,
      CHOOSER_Selected, 0,
    TAG_DONE),
//    CHILD_WeightedWidth, 0,
    CHILD_Label, IIntuition->NewObject(LabelClass, NULL,// "label.image",
      LABEL_Text, GetString(&li, MSG_GUI_SETTINGS_GFX_MEMMAP),//"_Memory map",
    TAG_DONE),
    LAYOUT_AddChild, OBJ(OID_PALNTSC) = IIntuition->NewObject(ChooserClass, NULL, //"chooser.gadget",
      //GA_ID,         OID_PALNTSC,
      //GA_RelVerify,  TRUE,
      GA_Underscore, 0,
      //CHOOSER_Labels,   &palntsc_list,
      CHOOSER_LabelArray, palntsc,
      CHOOSER_Selected, 0,
    TAG_DONE),
//    CHILD_WeightedWidth, 0,
    CHILD_Label, IIntuition->NewObject(LabelClass, NULL,// "label.image",
      LABEL_Text, GetString(&li, MSG_GUI_SETTINGS_GFX_VIDEO),//"Vide_o",
    TAG_DONE),
    LAYOUT_AddChild, OBJ(OID_OC_SFX) = IIntuition->NewObject(ChooserClass, NULL, //"chooser.gadget",
      //GA_ID,         OID_OC_SFX,
      //GA_RelVerify,  TRUE,
      GA_Underscore, 0,
      //CHOOSER_Labels,   &oc_sfx_list,
      CHOOSER_LabelArray, oc_sfx,
      CHOOSER_Selected, 0,
    TAG_DONE),
//    CHILD_WeightedWidth, 0,
    CHILD_Label, IIntuition->NewObject(LabelClass, NULL,// "label.image",
      LABEL_Text, GetString(&li, MSG_GUI_SETTINGS_GFX_OVERSFX),//"Overclock SuperF_X",
    TAG_DONE),
    LAYOUT_AddChild, OBJ(OID_NOOVERSCAN) = IIntuition->NewObject(CheckBoxClass, NULL, //"checkbox.gadget",
      //GA_ID,   OID_NOOVERSCAN,
      //GA_RelVerify, TRUE,
      GA_Text, GetString(&li, MSG_GUI_SETTINGS_NOOVERSCAN),//"No Overscan (320x240)",
      CHECKBOX_TextPlace, PLACETEXT_LEFT,
    TAG_DONE),
//    CHILD_WeightedWidth, 0,
    LAYOUT_AddChild, OBJ(OID_EMULATED) = IIntuition->NewObject(CheckBoxClass, NULL, //"checkbox.gadget",
      GA_ID,        OID_EMULATED,
      GA_RelVerify, TRUE,
      GA_Text,      GetString(&li, MSG_GUI_SETTINGS_EMULATED),//"Emulated machine",
      CHECKBOX_TextPlace, PLACETEXT_LEFT,
    TAG_DONE),
//    CHILD_WeightedWidth, 0,
    LAYOUT_AddChild, OBJ(OID_SKINS) = IIntuition->NewObject(ChooserClass, NULL, //"chooser.gadget",
      //GA_ID,         OID_SKINS,
      //GA_RelVerify,  TRUE,
      GA_Underscore, 0,
      //CHOOSER_Labels,   &skinfx_list,
      CHOOSER_LabelArray, skins,
      CHOOSER_Selected, 0,
    TAG_DONE),
//    CHILD_WeightedWidth, 0,
    CHILD_Label, IIntuition->NewObject(LabelClass, NULL,// "label.image",
      LABEL_Text, GetString(&li, MSG_GUI_SETTINGS_GFX_SKINS),//"Skins",
    TAG_DONE),
    LAYOUT_AddChild, OBJ(OID_DISP_RENDER) = IIntuition->NewObject(CheckBoxClass, NULL, //"checkbox.gadget",
      GA_ID,        OID_DISP_RENDER,
      GA_RelVerify, TRUE,
      GA_Text,      GetString(&li, MSG_GUI_SETTINGS_RENDER),//"Display type of render",
      CHECKBOX_TextPlace, PLACETEXT_LEFT,
    TAG_DONE),
//    CHILD_WeightedWidth, 0,
    LAYOUT_AddChild, OBJ(OID_RENDERTYPE) = IIntuition->NewObject(ChooserClass, NULL, //"chooser.gadget",
      GA_ID,         OID_RENDERTYPE,
      GA_RelVerify,  TRUE,
      GA_Underscore, 0,
      CHOOSER_Labels,   &render_list,
      CHOOSER_Selected, 0,
    TAG_DONE),
//    CHILD_WeightedWidth, 0,
    CHILD_Label, IIntuition->NewObject(LabelClass, NULL,// "label.image",
      LABEL_Text, GetString(&li, MSG_GUI_SETTINGS_GFX_RENDER),//"Type of render",
    TAG_DONE),
    LAYOUT_AddChild, OBJ(OID_FILTER) = IIntuition->NewObject(ChooserClass, NULL, //"chooser.gadget",
      //GA_ID,         OID_FILTER,
      //GA_RelVerify,  TRUE,
      GA_Underscore, 0,
      CHOOSER_Labels,   &filter_list,
      CHOOSER_Selected, 0,
    TAG_DONE),
//    CHILD_WeightedWidth, 0,
    CHILD_Label, IIntuition->NewObject(LabelClass, NULL,// "label.image",
      LABEL_Text, GetString(&li, MSG_GUI_SETTINGS_GFX_FILTERS),//"Filters",
    TAG_DONE),
    LAYOUT_AddChild, OBJ(OID_SHADERS) = IIntuition->NewObject(ChooserClass, NULL, //"chooser.gadget",
      //GA_ID,         OID_SHADERS,
      //GA_RelVerify,  TRUE,
      GA_Underscore, 0,
      CHOOSER_Labels,   &shader_list,
      CHOOSER_Selected, 0,
    TAG_DONE),
//    CHILD_WeightedWidth, 0,
    CHILD_Label, IIntuition->NewObject(LabelClass, NULL,// "label.image",
      LABEL_Text, GetString(&li, MSG_GUI_SETTINGS_GFX_SHADERS),//"Shaders",
    TAG_DONE),
    //LAYOUT_AddChild, IIntuition->NewObject(SpaceClass, NULL, TAG_DONE),
  TAG_DONE),
  CHILD_WeightedWidth, 0,

  LAYOUT_AddChild, IIntuition->NewObject(SpaceClass, NULL, TAG_DONE),

TAG_DONE), // END of 'Graphics Options'

#endif
