#ifndef GUI_AMIGAINPUT_H
#define GUI_AMIGAINPUT_H

            PAGE_Add, OBJ(OID_AMIGAINPUT) = IIntuition->NewObject(LayoutClass, NULL, //"layout.gadget",
             LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
             LAYOUT_SpaceOuter,  TRUE,
             //LAYOUT_SpaceInner,  FALSE,
// AMIGAINPUT: Player 1 Input Settings
             LAYOUT_AddChild, OBJ(OID_P1_OPTIONS) = IIntuition->NewObject(LayoutClass, NULL, //"layout.gadget",
              LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
              LAYOUT_SpaceOuter,  TRUE,
              //LAYOUT_SpaceInner,  FALSE,
              LAYOUT_BevelStyle,  BVS_GROUP,
              LAYOUT_Label,       GetString(&li, MSG_GUI_AI_P1_GROUP),//"Player 1 Input Settings",
              LAYOUT_AddChild, IIntuition->NewObject(LayoutClass, NULL, //"layout.gadget",
               //LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
               //LAYOUT_SpaceOuter,  TRUE,
               //LAYOUT_SpaceInner,  FALSE,
               LAYOUT_LabelColumn, PLACETEXT_RIGHT,
               LAYOUT_AddChild, OBJ(OID_P1_KJ) = IIntuition->NewObject(ChooserClass, NULL, //"chooser.gadget",
                //GA_ID,         OID_P1_KJ,
                //GA_RelVerify,  TRUE,
                GA_Underscore, 0,
                CHOOSER_Labels,   &player1_kj_list,
                CHOOSER_Selected, 0,
               TAG_DONE),
               CHILD_WeightedWidth, 0,
//               LAYOUT_AddChild, OBJ(OID_P1_STARTB) = IIntuition->NewObject(CheckBoxClass, NULL, //"checkbox.gadget",
//                GA_ID,        OID_P1_STARTB,
//                GA_RelVerify, TRUE,
//                GA_Text,      GetString(&li, MSG_GUI_AI_JOYPAD_SATRT_BTN),//"Joypad has start-button",
//                //CHECKBOX_TextPlace, PLACETEXT_LEFT,
//               TAG_DONE),
               CHILD_Label, IIntuition->NewObject(LabelClass, NULL,// "label.image",
                LABEL_SoftStyle, FSF_ITALIC,
                LABEL_Text,      GetString(&li, MSG_GUI_AI_BUTTON_REMAP),
               TAG_DONE),
              TAG_DONE), // END of key/Joy chooser+checkbox
              //CHILD_WeightedWidth, 0,
// AMIGAINPUT: Player 1 keys/buttons
              LAYOUT_AddChild, IIntuition->NewObject(LayoutClass, NULL, //"layout.gadget",
               //LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
               LAYOUT_SpaceOuter,  TRUE,
               //LAYOUT_SpaceInner,  FALSE,
               LAYOUT_AddChild, IIntuition->NewObject(LayoutClass, NULL, //"layout.gadget",
                LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
                LAYOUT_SpaceOuter,  TRUE,
                //LAYOUT_SpaceInner,  FALSE,
                LAYOUT_AddChild, OBJ(OID_P1_K_LF) = IIntuition->NewObject(StringClass, NULL,
                 STRINGA_MaxChars, 30,
                 STRINGA_HookType, SHK_HOTKEY,
                TAG_DONE),
                CHILD_Label, IIntuition->NewObject(LabelClass, NULL,
                 LABEL_Text, GetString(&li, MSG_GUI_AI_LEFT),//"Left:",
                TAG_DONE),
                LAYOUT_AddChild, OBJ(OID_P1_K_RI) = IIntuition->NewObject(StringClass, NULL,
                 STRINGA_MaxChars, 30,
                 STRINGA_HookType, SHK_HOTKEY,
                TAG_DONE),
                CHILD_Label, IIntuition->NewObject(LabelClass, NULL,
                 LABEL_Text, GetString(&li, MSG_GUI_AI_RIGHT),//"Right:",
                TAG_DONE),
                LAYOUT_AddChild, OBJ(OID_P1_K_UP) = IIntuition->NewObject(StringClass, NULL,
                 STRINGA_MaxChars, 30,
                 STRINGA_HookType, SHK_HOTKEY,
                TAG_DONE),
                CHILD_Label, IIntuition->NewObject(LabelClass, NULL,
                 LABEL_Text, GetString(&li, MSG_GUI_AI_UP),//"Up:",
                TAG_DONE),
                LAYOUT_AddChild, OBJ(OID_P1_K_DW) = IIntuition->NewObject(StringClass, NULL,
                 STRINGA_MaxChars, 30,
                 STRINGA_HookType, SHK_HOTKEY,
                TAG_DONE),
                CHILD_Label, IIntuition->NewObject(LabelClass, NULL,
                 LABEL_Text, GetString(&li, MSG_GUI_AI_DOWN),//"Down:",
                TAG_DONE),
               TAG_DONE), // END of buttons: left, right, up, down
               CHILD_ScaleWidth, 50,
               LAYOUT_AddChild, IIntuition->NewObject(LayoutClass, NULL, //"layout.gadget",
                LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
                LAYOUT_SpaceOuter,  TRUE,
                //LAYOUT_SpaceInner,  FALSE,
                LAYOUT_AddChild, OBJ(OID_P1_K_A) = IIntuition->NewObject(StringClass, NULL,
                 STRINGA_MaxChars, 30,
                 STRINGA_HookType, SHK_HOTKEY,
                TAG_DONE),
                CHILD_Label, IIntuition->NewObject(LabelClass, NULL,
                 LABEL_Text, GetString(&li, MSG_GUI_AI_BTN_A),//"A-button:",
                TAG_DONE),
                LAYOUT_AddChild, OBJ(OID_P1_K_B) = IIntuition->NewObject(StringClass, NULL,
                 STRINGA_MaxChars, 30,
                 STRINGA_HookType, SHK_HOTKEY,
                TAG_DONE),
                CHILD_Label, IIntuition->NewObject(LabelClass, NULL,
                 LABEL_Text, GetString(&li, MSG_GUI_AI_BTN_B),//"B-button:",
                TAG_DONE),
                LAYOUT_AddChild, OBJ(OID_P1_K_X) = IIntuition->NewObject(StringClass, NULL,
                 STRINGA_MaxChars, 30,
                 STRINGA_HookType, SHK_HOTKEY,
                TAG_DONE),
                CHILD_Label, IIntuition->NewObject(LabelClass, NULL,
                 LABEL_Text, GetString(&li, MSG_GUI_AI_BTN_X),//"X-button:",
                TAG_DONE),
                LAYOUT_AddChild, OBJ(OID_P1_K_Y) = IIntuition->NewObject(StringClass, NULL,
                 STRINGA_MaxChars, 30,
                 STRINGA_HookType, SHK_HOTKEY,
                TAG_DONE),
                CHILD_Label, IIntuition->NewObject(LabelClass, NULL,
                 LABEL_Text, GetString(&li, MSG_GUI_AI_BTN_Y),//"Y-button:",
                TAG_DONE),
               TAG_DONE), // END of buttons: A, B, X, Y
               LAYOUT_AddChild, OBJ(OID_P1_KJ_BTN0) = IIntuition->NewObject(LayoutClass, NULL, //"layout.gadget",
                LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
                LAYOUT_AddChild, OBJ(OID_P1_BTN_A) = IIntuition->NewObject(ButtonClass, NULL, //"button.gadget",
                 GA_ID,        OID_P1_BTN_A,
                 GA_RelVerify, TRUE,
                 GA_Text,      "B%ld",
                 BUTTON_VarArgs,      &cfg_value[_PLAYER1_BTN_A],
                 BUTTON_PushButton,   TRUE,
                 BUTTON_DomainString, "B8",
                TAG_DONE),
                //CHILD_WeightedWidth, 0,
                LAYOUT_AddChild, OBJ(OID_P1_BTN_B) = IIntuition->NewObject(ButtonClass, NULL, //"button.gadget",
                 GA_ID,        OID_P1_BTN_B,
                 GA_RelVerify, TRUE,
                 GA_Text,      "B%ld",
                 BUTTON_VarArgs,      &cfg_value[_PLAYER1_BTN_B],
                 BUTTON_PushButton,   TRUE,
                 BUTTON_DomainString, "B8",
                TAG_DONE),
                //CHILD_WeightedWidth, 0,
                LAYOUT_AddChild, OBJ(OID_P1_BTN_X) = IIntuition->NewObject(ButtonClass, NULL, //"button.gadget",
                 GA_ID,        OID_P1_BTN_X,
                 GA_RelVerify, TRUE,
                 GA_Text,      "B%ld",
                 BUTTON_VarArgs,      &cfg_value[_PLAYER1_BTN_X],
                 BUTTON_PushButton,   TRUE,
                 BUTTON_DomainString, "B8",
                TAG_DONE),
                //CHILD_WeightedWidth, 0,
                LAYOUT_AddChild, OBJ(OID_P1_BTN_Y) = IIntuition->NewObject(ButtonClass, NULL, //"button.gadget",
                 GA_ID,        OID_P1_BTN_Y,
                 GA_RelVerify, TRUE,
                 GA_Text,      "B%ld",
                 BUTTON_VarArgs,      &cfg_value[_PLAYER1_BTN_Y],
                 BUTTON_PushButton,   TRUE,
                 BUTTON_DomainString, "B8",
                TAG_DONE),
                //CHILD_WeightedWidth, 0,
               TAG_DONE), // END of choosers: A, B, X, Y
               CHILD_WeightedWidth, 0,
               LAYOUT_AddChild, IIntuition->NewObject(LayoutClass, NULL, //"layout.gadget",
                LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
                LAYOUT_SpaceOuter,  TRUE,
                //LAYOUT_SpaceInner,  FALSE,
                LAYOUT_AddChild, OBJ(OID_P1_K_L) = IIntuition->NewObject(StringClass, NULL,
                 STRINGA_MaxChars, 30,
                 STRINGA_HookType, SHK_HOTKEY,
                TAG_DONE),
                CHILD_Label, IIntuition->NewObject(LabelClass, NULL,
                 LABEL_Text, GetString(&li, MSG_GUI_AI_BTN_L),//"L-button:",
                TAG_DONE),
                LAYOUT_AddChild, OBJ(OID_P1_K_R) = IIntuition->NewObject(StringClass, NULL,
                 STRINGA_MaxChars, 30,
                 STRINGA_HookType, SHK_HOTKEY,
                TAG_DONE),
                CHILD_Label, IIntuition->NewObject(LabelClass, NULL,
                 LABEL_Text, GetString(&li, MSG_GUI_AI_BTN_R),//"R-button:",
                TAG_DONE),
                LAYOUT_AddChild, OBJ(OID_P1_K_SEL) = IIntuition->NewObject(StringClass, NULL,
                 STRINGA_MaxChars, 30,
                 STRINGA_HookType, SHK_HOTKEY,
                TAG_DONE),
                CHILD_Label, IIntuition->NewObject(LabelClass, NULL,
                 LABEL_Text, GetString(&li, MSG_GUI_AI_SELECT),//"Select:",
                TAG_DONE),
                LAYOUT_AddChild, OBJ(OID_P1_K_STA) = IIntuition->NewObject(StringClass, NULL,
                 STRINGA_MaxChars, 30,
                 STRINGA_HookType, SHK_HOTKEY,
                TAG_DONE),
                CHILD_Label, IIntuition->NewObject(LabelClass, NULL,
                 LABEL_Text, GetString(&li, MSG_GUI_AI_START),//"Start:",
                TAG_DONE),
               TAG_DONE), // END of buttons: L, R, select, start
               LAYOUT_AddChild, OBJ(OID_P1_KJ_BTN1) = IIntuition->NewObject(LayoutClass, NULL, //"layout.gadget",
                LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
                LAYOUT_AddChild, OBJ(OID_P1_BTN_L) = IIntuition->NewObject(ButtonClass, NULL, //"button.gadget",
                 GA_ID,        OID_P1_BTN_L,
                 GA_RelVerify, TRUE,
                 GA_Text,      "B%ld",
                 BUTTON_VarArgs,      &cfg_value[_PLAYER1_BTN_L],
                 BUTTON_PushButton,   TRUE,
                 BUTTON_DomainString, "B8",
                TAG_DONE),
                //CHILD_WeightedWidth, 0,
                LAYOUT_AddChild, OBJ(OID_P1_BTN_R) = IIntuition->NewObject(ButtonClass, NULL, //"button.gadget",
                 GA_ID,        OID_P1_BTN_R,
                 GA_RelVerify, TRUE,
                 GA_Text,      "B%ld",
                 BUTTON_VarArgs,      &cfg_value[_PLAYER1_BTN_R],
                 BUTTON_PushButton,   TRUE,
                 BUTTON_DomainString, "B8",
                TAG_DONE),
                //CHILD_WeightedWidth, 0,
                LAYOUT_AddChild, OBJ(OID_P1_BTN_SEL) = IIntuition->NewObject(ButtonClass, NULL, //"button.gadget",
                 GA_ID,        OID_P1_BTN_SEL,
                 GA_RelVerify, TRUE,
                 GA_Text,      "B%ld",
                 BUTTON_VarArgs,      &cfg_value[_PLAYER1_BTN_SEL],
                 BUTTON_PushButton,   TRUE,
                 BUTTON_DomainString, "B8",
                TAG_DONE),
                //CHILD_WeightedWidth, 0,
                LAYOUT_AddChild, OBJ(OID_P1_BTN_STA) = IIntuition->NewObject(ButtonClass, NULL, //"button.gadget",
                 GA_ID,        OID_P1_BTN_STA,
                 GA_RelVerify, TRUE,
                 GA_Text,      "B%ld",
                 BUTTON_VarArgs,      &cfg_value[_PLAYER1_BTN_STA],
                 BUTTON_PushButton,   TRUE,
                 BUTTON_DomainString, "B8",
                TAG_DONE),
                //CHILD_WeightedWidth, 0,
               TAG_DONE), // END of choosers: L, R, select, start
               CHILD_WeightedWidth, 0,
              TAG_DONE), // END of 'Player 1 Input Settings GROUP
             TAG_DONE),
             CHILD_WeightedHeight, 0,
             LAYOUT_AddChild, IIntuition->NewObject(LayoutClass, NULL, //"layout.gadget",
              //LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
              LAYOUT_SpaceOuter, TRUE,
              //LAYOUT_SpaceInner,  FALSE,
              OBJ(OID_JOYPAD_IMG)? LAYOUT_AddImage : TAG_IGNORE, OBJ(OID_JOYPAD_IMG),
             TAG_DONE),
             //CHILD_NoDispose, TRUE,
             //CHILD_WeightedHeight, 0,
// AMIGAINPUT: Player 2 Input Settings
             LAYOUT_AddChild, OBJ(OID_P2_OPTIONS) = IIntuition->NewObject(LayoutClass, NULL, //"layout.gadget",
              LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
              LAYOUT_SpaceOuter,  TRUE,
              //LAYOUT_SpaceInner,  FALSE,
              LAYOUT_BevelStyle,  BVS_GROUP,
              LAYOUT_Label,       GetString(&li, MSG_GUI_AI_P2_GROUP),//"Player 2 Input Settings",
              //LAYOUT_AddChild, OBJ(OID_P2_OPTIONS) = IIntuition->NewObject(LayoutClass, NULL, //"layout.gadget",
              LAYOUT_AddChild, IIntuition->NewObject(LayoutClass, NULL, //"layout.gadget",
               //LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
               //LAYOUT_SpaceOuter,  TRUE,
               //LAYOUT_SpaceInner,  FALSE,
               LAYOUT_LabelColumn, PLACETEXT_RIGHT,
               LAYOUT_AddChild, OBJ(OID_P2_KJ) = IIntuition->NewObject(ChooserClass, NULL, //"chooser.gadget",
                GA_ID,         OID_P2_KJ,
                //GA_RelVerify,  TRUE,
                GA_Underscore, 0,
                CHOOSER_Labels,   &player2_kj_list,
                CHOOSER_Selected, 0,
               TAG_DONE),
               CHILD_WeightedWidth, 0,
//               LAYOUT_AddChild, OBJ(OID_P2_STARTB) = IIntuition->NewObject(CheckBoxClass, NULL, //"checkbox.gadget",
//                GA_ID,        OID_P2_STARTB,
//                GA_RelVerify, TRUE,
//                GA_Text,      GetString(&li, MSG_GUI_AI_JOYPAD_SATRT_BTN),//"Joypad has start-button",
//                //CHECKBOX_TextPlace, PLACETEXT_LEFT,
//               TAG_DONE),
               //CHILD_WeightedWidth, 0,
              CHILD_Label, IIntuition->NewObject(LabelClass, NULL,// "label.image",
               LABEL_SoftStyle, FSF_ITALIC,
               LABEL_Text, GetString(&li, MSG_GUI_AI_BUTTON_REMAP),
              TAG_DONE),
           /*LAYOUT_AddChild, IIntuition->NewObject(ButtonClass, NULL,
            GA_Text,       GetString(&li, MSG_GUI_AI_BUTTON_REMAP),
            GA_ReadOnly,   TRUE,
            GA_Underscore, 0,
            BUTTON_BevelStyle,    BVS_NONE,
            BUTTON_Transparent,   TRUE,
            BUTTON_SoftStyle,     FSF_ITALIC,
            BUTTON_Justification, BCJ_CENTER,
           TAG_DONE),*/
              TAG_DONE), // END of key/Joy chooser+checkbox group
              //CHILD_WeightedWidth, 0,
// AMIGAINPUT: Player 2 keys/buttons
              LAYOUT_AddChild, OBJ(OID_P2_KJ_COLS) = IIntuition->NewObject(LayoutClass, NULL, //"layout.gadget",
               LAYOUT_SpaceOuter,  TRUE,
               //LAYOUT_SpaceInner,  FALSE,
               LAYOUT_AddChild, /*OBJ(OID_P2_K_COL0) =*/ IIntuition->NewObject(LayoutClass, NULL, //"layout.gadget",
                LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
                LAYOUT_SpaceOuter,  TRUE,
                //LAYOUT_SpaceInner,  FALSE,
                LAYOUT_AddChild, OBJ(OID_P2_K_LF) = IIntuition->NewObject(StringClass, NULL,
                 STRINGA_MaxChars, 30,
                 STRINGA_HookType, SHK_HOTKEY,
                TAG_DONE),
                CHILD_Label, IIntuition->NewObject(LabelClass, NULL,
                 LABEL_Text, GetString(&li, MSG_GUI_AI_LEFT),//"Left:",
                TAG_DONE),
                LAYOUT_AddChild, OBJ(OID_P2_K_RI) = IIntuition->NewObject(StringClass, NULL,
                 STRINGA_MaxChars, 30,
                 STRINGA_HookType, SHK_HOTKEY,
                TAG_DONE),
                CHILD_Label, IIntuition->NewObject(LabelClass, NULL,
                 LABEL_Text, GetString(&li, MSG_GUI_AI_RIGHT),//"Right:",
                TAG_DONE),
                LAYOUT_AddChild, OBJ(OID_P2_K_UP) = IIntuition->NewObject(StringClass, NULL,
                 STRINGA_MaxChars, 30,
                 STRINGA_HookType, SHK_HOTKEY,
                TAG_DONE),
                CHILD_Label, IIntuition->NewObject(LabelClass, NULL,
                 LABEL_Text, GetString(&li, MSG_GUI_AI_UP),//"Up:",
                TAG_DONE),
                LAYOUT_AddChild, OBJ(OID_P2_K_DW) = IIntuition->NewObject(StringClass, NULL,
                 STRINGA_MaxChars, 30,
                 STRINGA_HookType, SHK_HOTKEY,
                TAG_DONE),
                CHILD_Label, IIntuition->NewObject(LabelClass, NULL,
                 LABEL_Text, GetString(&li, MSG_GUI_AI_DOWN),//"Down:",
                TAG_DONE),
               TAG_DONE), // END of buttons: left, right, up, down
               CHILD_ScaleWidth, 50,
               LAYOUT_AddChild, /*OBJ(OID_P2_K_COL1) =*/ IIntuition->NewObject(LayoutClass, NULL, //"layout.gadget",
                LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
                LAYOUT_SpaceOuter,  TRUE,
                //LAYOUT_SpaceInner,  FALSE,
                LAYOUT_AddChild, OBJ(OID_P2_K_A) = IIntuition->NewObject(StringClass, NULL,
                 STRINGA_MaxChars, 30,
                 STRINGA_HookType, SHK_HOTKEY,
                TAG_DONE),
                CHILD_Label, IIntuition->NewObject(LabelClass, NULL,
                 LABEL_Text, GetString(&li, MSG_GUI_AI_BTN_A),//"A-button:",
                TAG_DONE),
                LAYOUT_AddChild, OBJ(OID_P2_K_B) = IIntuition->NewObject(StringClass, NULL,
                 STRINGA_MaxChars, 30,
                 STRINGA_HookType, SHK_HOTKEY,
                TAG_DONE),
                CHILD_Label, IIntuition->NewObject(LabelClass, NULL,
                 LABEL_Text, GetString(&li, MSG_GUI_AI_BTN_B),//"B-button:",
                TAG_DONE),
                LAYOUT_AddChild, OBJ(OID_P2_K_X) = IIntuition->NewObject(StringClass, NULL,
                 STRINGA_MaxChars, 30,
                 STRINGA_HookType, SHK_HOTKEY,
                TAG_DONE),
                CHILD_Label, IIntuition->NewObject(LabelClass, NULL,
                 LABEL_Text, GetString(&li, MSG_GUI_AI_BTN_X),//"X-button:",
                TAG_DONE),
                LAYOUT_AddChild, OBJ(OID_P2_K_Y) = IIntuition->NewObject(StringClass, NULL,
                 STRINGA_MaxChars, 30,
                 STRINGA_HookType, SHK_HOTKEY,
                TAG_DONE),
                CHILD_Label, IIntuition->NewObject(LabelClass, NULL,
                 LABEL_Text, GetString(&li, MSG_GUI_AI_BTN_Y),//"Y-button:",
                TAG_DONE),
               TAG_DONE), // END of buttons: A, B, X, Y
               LAYOUT_AddChild, /*OBJ(OID_P2_KJ_BTN0) =*/ IIntuition->NewObject(LayoutClass, NULL, //"layout.gadget",
                LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
                LAYOUT_AddChild, OBJ(OID_P2_BTN_A) = IIntuition->NewObject(ButtonClass, NULL, //"button.gadget",
                 GA_ID,        OID_P2_BTN_A,
                 GA_RelVerify, TRUE,
                 GA_Text,      "B%ld",
                 BUTTON_VarArgs,      &cfg_value[_PLAYER2_BTN_A],
                 BUTTON_PushButton,   TRUE,
                 BUTTON_DomainString, "B8",
                TAG_DONE),
                //CHILD_WeightedWidth, 0,
                LAYOUT_AddChild, OBJ(OID_P2_BTN_B) = IIntuition->NewObject(ButtonClass, NULL, //"button.gadget",
                 GA_ID,        OID_P2_BTN_B,
                 GA_RelVerify, TRUE,
                 GA_Text,      "B%ld",
                 BUTTON_VarArgs,      &cfg_value[_PLAYER2_BTN_B],
                 BUTTON_PushButton,   TRUE,
                 BUTTON_DomainString, "B8",
                TAG_DONE),
                //CHILD_WeightedWidth, 0,
                LAYOUT_AddChild, OBJ(OID_P2_BTN_X) = IIntuition->NewObject(ButtonClass, NULL, //"button.gadget",
                 GA_ID,        OID_P2_BTN_X,
                 GA_RelVerify, TRUE,
                 GA_Text,      "B%ld",
                 BUTTON_VarArgs,      &cfg_value[_PLAYER2_BTN_X],
                 BUTTON_PushButton,   TRUE,
                 BUTTON_DomainString, "B8",
                TAG_DONE),
                //CHILD_WeightedWidth, 0,
                LAYOUT_AddChild, OBJ(OID_P2_BTN_Y) = IIntuition->NewObject(ButtonClass, NULL, //"button.gadget",
                 GA_ID,        OID_P2_BTN_Y,
                 GA_RelVerify, TRUE,
                 GA_Text,      "B%ld",
                 BUTTON_VarArgs,      &cfg_value[_PLAYER2_BTN_Y],
                 BUTTON_PushButton,   TRUE,
                 BUTTON_DomainString, "B8",
                TAG_DONE),
                //CHILD_WeightedWidth, 0,
               TAG_DONE), // END of choosers: A, B, X, Y
               CHILD_WeightedWidth, 0,
               LAYOUT_AddChild, /*OBJ(OID_P2_K_COL2) =*/ IIntuition->NewObject(LayoutClass, NULL, //"layout.gadget",
                LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
                LAYOUT_SpaceOuter,  TRUE,
                //LAYOUT_SpaceInner,  FALSE,
                LAYOUT_AddChild, OBJ(OID_P2_K_L) = IIntuition->NewObject(StringClass, NULL,
                 STRINGA_MaxChars, 30,
                 STRINGA_HookType, SHK_HOTKEY,
                TAG_DONE),
                CHILD_Label, IIntuition->NewObject(LabelClass, NULL,
                 LABEL_Text, GetString(&li, MSG_GUI_AI_BTN_L),//"L-button:",
                TAG_DONE),
                LAYOUT_AddChild, OBJ(OID_P2_K_R) = IIntuition->NewObject(StringClass, NULL,
                 STRINGA_MaxChars, 30,
                 STRINGA_HookType, SHK_HOTKEY,
                TAG_DONE),
                CHILD_Label, IIntuition->NewObject(LabelClass, NULL,
                 LABEL_Text, GetString(&li, MSG_GUI_AI_BTN_R),//"R-button:",
                TAG_DONE),
                LAYOUT_AddChild, OBJ(OID_P2_K_SEL) = IIntuition->NewObject(StringClass, NULL,
                 STRINGA_MaxChars, 30,
                 STRINGA_HookType, SHK_HOTKEY,
                TAG_DONE),
                CHILD_Label, IIntuition->NewObject(LabelClass, NULL,
                 LABEL_Text, GetString(&li, MSG_GUI_AI_SELECT),//"Select:",
                TAG_DONE),
                LAYOUT_AddChild, OBJ(OID_P2_K_STA) = IIntuition->NewObject(StringClass, NULL,
                 STRINGA_MaxChars, 30,
                 STRINGA_HookType, SHK_HOTKEY,
                TAG_DONE),
                CHILD_Label, IIntuition->NewObject(LabelClass, NULL,
                 LABEL_Text, GetString(&li, MSG_GUI_AI_START),//"Start:",
                TAG_DONE),
               TAG_DONE), // END of buttons: L, R, select, start
               LAYOUT_AddChild, /*OBJ(OID_P2_KJ_BTN1) =*/ IIntuition->NewObject(LayoutClass, NULL, //"layout.gadget",
                LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
                LAYOUT_AddChild, OBJ(OID_P2_BTN_L) = IIntuition->NewObject(ButtonClass, NULL, //"button.gadget",
                 GA_ID,        OID_P2_BTN_L,
                 GA_RelVerify, TRUE,
                 GA_Text,      "B%ld",
                 BUTTON_VarArgs,      &cfg_value[_PLAYER2_BTN_L],
                 BUTTON_PushButton,   TRUE,
                 BUTTON_DomainString, "B8",
                TAG_DONE),
                //CHILD_WeightedWidth, 0,
                LAYOUT_AddChild, OBJ(OID_P2_BTN_R) = IIntuition->NewObject(ButtonClass, NULL, //"button.gadget",
                 GA_ID,        OID_P2_BTN_R,
                 GA_RelVerify, TRUE,
                 GA_Text,      "B%ld",
                 BUTTON_VarArgs,      &cfg_value[_PLAYER2_BTN_R],
                 BUTTON_PushButton,   TRUE,
                 BUTTON_DomainString, "B8",
                TAG_DONE),
                //CHILD_WeightedWidth, 0,
                LAYOUT_AddChild, OBJ(OID_P2_BTN_SEL) = IIntuition->NewObject(ButtonClass, NULL, //"button.gadget",
                 GA_ID,        OID_P2_BTN_SEL,
                 GA_RelVerify, TRUE,
                 GA_Text,      "B%ld",
                 BUTTON_VarArgs,      &cfg_value[_PLAYER2_BTN_SEL],
                 BUTTON_PushButton,   TRUE,
                 BUTTON_DomainString, "B8",
                TAG_DONE),
                //CHILD_WeightedWidth, 0,
                LAYOUT_AddChild, OBJ(OID_P2_BTN_STA) = IIntuition->NewObject(ButtonClass, NULL, //"button.gadget",
                 GA_ID,        OID_P2_BTN_STA,
                 GA_RelVerify, TRUE,
                 GA_Text,      "B%ld",
                 BUTTON_VarArgs,      &cfg_value[_PLAYER2_BTN_STA],
                 BUTTON_PushButton,   TRUE,
                 BUTTON_DomainString, "B8",
                TAG_DONE),
                //CHILD_WeightedWidth, 0,
               TAG_DONE), // END of choosers: L, R, select, start
               CHILD_WeightedWidth, 0,
              TAG_DONE), // END of buttons strings
             TAG_DONE), // END of 'Player 2 Input Settings GROUP
             CHILD_WeightedHeight, 0,
            TAG_DONE), // END of AmigaInput page/tab

#endif
