#ifndef GUI_SETTINGS_MISC_H
#define GUI_SETTINGS_MISC_H

             LAYOUT_AddChild, OBJ(OID_MISC_OPTIONS) = IIntuition->NewObject(LayoutClass, NULL, //"layout.gadget",
              //LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
              LAYOUT_SpaceOuter,     TRUE,
              LAYOUT_BevelStyle,     BVS_SBAR_VERT,//BVS_GROUP,
              LAYOUT_Label,          GetString(&li, MSG_GUI_SETTINGS_MISC_GROUP),//"Miscellaneous Options",
              LAYOUT_HorizAlignment, LALIGN_CENTER,
              LAYOUT_AddChild, OBJ(OID_FPS) = IIntuition->NewObject(CheckBoxClass, NULL, //"checkbox.gadget",
               GA_ID,        OID_FPS,
               //GA_RelVerify, TRUE,
               GA_Text,      GetString(&li, MSG_GUI_SETTINGS_MISC_FPS),//"Show _FPS",
               CHECKBOX_TextPlace, PLACETEXT_LEFT,
              TAG_DONE),
              CHILD_WeightedWidth, 0,
              LAYOUT_AddChild, OBJ(OID_DISP_TIME) = IIntuition->NewObject(CheckBoxClass, NULL, //"checkbox.gadget",
               GA_ID,   OID_DISP_TIME,
               //GA_RelVerify, TRUE,
               GA_Text, GetString(&li, MSG_GUI_SETTINGS_TIME),//"Display Time",
               CHECKBOX_TextPlace, PLACETEXT_LEFT,
              TAG_DONE),
              CHILD_WeightedWidth, 0,
              LAYOUT_AddChild, OBJ(OID_VSYNC) = IIntuition->NewObject(CheckBoxClass, NULL, //"checkbox.gadget",
               GA_ID,        OID_VSYNC,
               //GA_RelVerify, TRUE,
               GA_Text,      GetString(&li, MSG_GUI_SETTINGS_VSYNC),//"VSync on Snes9x",
               CHECKBOX_TextPlace, PLACETEXT_LEFT,
              TAG_DONE),
              CHILD_WeightedWidth, 0,
              LAYOUT_AddChild, OBJ(OID_OC_CPU) = IIntuition->NewObject(CheckBoxClass, NULL, //"checkbox.gadget",
               GA_ID,   OID_OC_CPU,
               //GA_RelVerify, TRUE,
               GA_Text, GetString(&li, MSG_GUI_SETTINGS_OVERCLOCK),//"Overclock CPU Snes9x",
               CHECKBOX_TextPlace, PLACETEXT_LEFT,
              TAG_DONE),
              CHILD_WeightedWidth, 0,
             TAG_DONE), // END of 'Miscellaneous Options'
             //CHILD_WeightedHeight, 0,

#endif
