#ifndef GUI_ABOUT_H
#define GUI_ABOUT_H

            PAGE_Add, IIntuition->NewObject(LayoutClass, NULL, //"layout.gadget",
             LAYOUT_Orientation,    LAYOUT_ORIENT_VERT,
             LAYOUT_SpaceOuter,     TRUE,
             //LAYOUT_SpaceInner,     FALSE,
             LAYOUT_HorizAlignment, LALIGN_CENTER,
             LAYOUT_VertAlignment,  LALIGN_CENTER,
             LAYOUT_AddImage, OBJ(OID_ABOUT) = IIntuition->NewObject(LabelClass, NULL, //"label.image",
              IA_Font, screen->Font,
              //LABEL_DrawInfo,      drinfo,
              LABEL_Underscore,    0,
              LABEL_Justification, LJ_CENTER,
              //LABEL_VerticalSpacing, 5,
              //LABEL_WordWrap,      0,
              LABEL_SoftStyle,     FSF_UNDERLINED,
              LABEL_Text,          VERS" "DATE"\n",
              LABEL_SoftStyle,     FSF_BOLD,
              //LABEL_WordWrap,      80,
              LABEL_Text,          GetString(&li, MSG_GUI_ABOUT_TXT01),
              LABEL_SoftStyle,     FSF_ITALIC,
              LABEL_Text,          GetString(&li, MSG_GUI_ABOUT_TXT02),
              LABEL_SoftStyle,     FS_NORMAL,
              LABEL_Text,          GetString(&li, MSG_GUI_ABOUT_TXT03),
             TAG_DONE),
             //CHILD_WeightedWidth, 0,
             LAYOUT_AddChild, IIntuition->NewObject(LayoutClass, NULL, //"layout.gadget",
              LAYOUT_Orientation,    LAYOUT_ORIENT_VERT,
              //LAYOUT_SpaceOuter,     TRUE,
              LAYOUT_HorizAlignment, LALIGN_CENTER,

              LAYOUT_AddChild, IIntuition->NewObject(SpaceClass, NULL, TAG_DONE),

              LAYOUT_AddChild, OBJ(OID_DONATE_BTN) = IIntuition->NewObject(ButtonClass, NULL, //"button.gadget",
                GA_ID,        OID_DONATE_BTN,
                GA_RelVerify, TRUE,
                //GA_Text, "PayPal DONATION",
                //BUTTON_Transparent, TRUE,
                //BUTTON_BevelStyle,  BVS_NONE,
                BUTTON_RenderImage, OBJ(OID_DONATE_IMG) = IIntuition->NewObject(BitMapClass, NULL, //"bitmap.image",
                  BITMAP_SourceFile, DATAS"/paypal.png",
                  BITMAP_Screen,     screen,
                  BITMAP_Masking,    TRUE,
                TAG_DONE),
              TAG_DONE),
              CHILD_WeightedWidth,  0,
              CHILD_WeightedHeight, 0,

              LAYOUT_AddChild, IIntuition->NewObject(SpaceClass, NULL, TAG_DONE),

              LAYOUT_AddChild, IIntuition->NewObject(ButtonClass, NULL, //"button.gadget",
                GA_ReadOnly, TRUE,
                BUTTON_Transparent, TRUE,
                BUTTON_BevelStyle,  BVS_NONE,
                BUTTON_RenderImage, OBJ(OID_ABOUT1_IMG) = IIntuition->NewObject(BitMapClass, NULL, //"bitmap.image",
                  BITMAP_SourceFile, DATAS"/sfc_logo.png",
                  BITMAP_Screen,     screen,
                  BITMAP_Masking,    TRUE,
                TAG_DONE),
              TAG_DONE),
              //CHILD_WeightedHeight, 0,
              CHILD_WeightedWidth,  0,
              LAYOUT_AddChild, IIntuition->NewObject(ButtonClass, NULL, //"button.gadget",
                GA_ReadOnly, TRUE,
                BUTTON_Transparent, TRUE,
                BUTTON_BevelStyle,  BVS_NONE,
                BUTTON_RenderImage, OBJ(OID_ABOUT2_IMG) = IIntuition->NewObject(BitMapClass, NULL, //"bitmap.image",
                  BITMAP_SourceFile, DATAS"/snes_logo.png",
                  BITMAP_Screen,     screen,
                  BITMAP_Masking,    TRUE,
                TAG_DONE),
              TAG_DONE),
             //CHILD_WeightedHeight, 0,
             CHILD_WeightedWidth,  0,
/*
              LAYOUT_AddImage, OBJ(OID_ABOUT1_IMG) = IIntuition->NewObject(BitMapClass, NULL, //"bitmap.image",
               BITMAP_SourceFile, DATAS"/sfc_logo.png",
               BITMAP_Screen,     screen,
               BITMAP_Masking,    TRUE,
              TAG_DONE),
              //CHILD_NoDispose,TRUE,
              LAYOUT_AddImage, OBJ(OID_ABOUT2_IMG) = IIntuition->NewObject(BitMapClass, NULL, //"bitmap.image",
               BITMAP_SourceFile, DATAS"/snes_logo.png",
               BITMAP_Screen,     screen,
               BITMAP_Masking,    TRUE,
              TAG_DONE),
              //CHILD_NoDispose,TRUE,
*/
             TAG_DONE),
             //CHILD_WeightedHeight, 0,
            TAG_DONE), // END of ABOUT page/tab

#endif
